# Test workflow must be triggered by push event
name: Test Workflow
on: [push]

# Jobs of the test's workflow
jobs:
    # Print the current stage
    notif-start:
        run-on: ubuntu-22.04
        steps:
          - run: echo "Start tests."

          
